</div>

<footer>
<div id="footer"><span class="priv">dd-team © 2012 | <a
    href="#">Privacy Policy</a></span> <!--{%FOOTER_LINK} --></div>
<!-- end footer -->
</footer>
<script type="text/javascript"> Cufon.now(); </script>


<div style="top: 279px; left: 624.5px;" class="pp_pic_holder facebook"
    id="pretty">
<div class="pp_top">
<div class="pp_left"></div>
<div class="pp_middle"></div>
<div class="pp_right"></div>
</div>
<div class="pp_content_container">
<div class="pp_left">
<div class="pp_right">
<div class="pp_content">
<div class="pp_loaderIcon"></div>
<div class="pp_fade"><a href="#" class="pp_expand"
    title="Expand the image">Expand</a>
<div class="pp_hoverContainer"><a class="pp_next" href="#">next</a>
<a class="pp_previous" href="#">previous</a></div>
<div id="pp_full_res"></div>
<div class="pp_details clearfix"><a class="pp_close" href="#">Close</a>
<p class="pp_description"></p>
<div class="pp_nav"><a href="#" class="pp_arrow_previous">Previous</a>
<p class="currentTextHolder">Image 0 of 0</p>
<a href="#" class="pp_arrow_next">Next</a></div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="pp_bottom">
<div class="pp_left"></div>
<div class="pp_middle"></div>
<div class="pp_right"></div>
</div>
</div>
<div style="opacity: 0; height: 1294px;" class="pp_overlay"></div>
<div style="top: 279px; left: 644.5px;" class="ppt"></div>
</body>
</html>